# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /worker

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
COPY src src

WORKDIR "/src"
RUN rm -rf PublicDataCollector.WebApi

WORKDIR "/src/PublicDataCollector.Worker"
RUN dotnet build "./PublicDataCollector.Worker.csproj" -c $BUILD_CONFIGURATION -o /worker/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./PublicDataCollector.Worker.csproj" -c $BUILD_CONFIGURATION -o /worker/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /worker
COPY --from=publish /worker/publish .
ENTRYPOINT ["dotnet", "PublicDataCollector.Worker.dll"]
