services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@admin123#"
      ACCEPT_EULA: "Y"
    restart: always
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "sqlserver", "-U", "sa", "-P", "@admin123#", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - sqlvolume:/var/opt/mssql
      - ./scripts/init.sql:/init.sql:ro

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./scripts/init.sql:/init.sql:ro
    entrypoint: >
      bash -c "
        echo '⏳ Waiting SQL Server...';
        sleep 20;
        /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P '@admin123#' -i /init.sql;
        echo '✅ Data base created!'; "
  
  backend:
    build:
      context: .
    container_name: backend
    restart: always
    environment:
      ASPNETCORE_URLS: http://+
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 8080:80
    depends_on:
      - sqlserver
      - db-init

  worker:
    build:
      context: .
      dockerfile: Dockerfile-Worker
    container_name: worker
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - sqlserver
      - db-init

  web:
    build:
      context: ./front-end/rates-app
    container_name: web
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  sqlvolume:
